### PR TITLE
Fixed typos in env variables

### PR DESCRIPTION
**Pull request by TheBloodMan49**
Also removed a "readonly" tag on a volume because it's subdirectory can't be readonly

### CODE REVIEW

**Review by Lugrim — COMMENTED** [review]
It may work, but I still can't start prod for some reason, probably because of the frontend Dockerfile

**Comment by Dyskal** [comment]
where is STATIC_MEDIA used ? isn't it MEDIA_ROOT ?
(https://github.com/InsaLan/backend-insalan.fr/blob/3e431d1e1ef7ed307d750ae9b102dd66d8a7ea2a/insalan/settings.py#L178C2-L178C2)

**Comment by TheBloodMan49** [comment]
Unfortunately I can't make the prod environment work currently as we need to decide on how to bundle the frontend

**Comment by TheBloodMan49** [comment]
> So, if I understood right, are media and static supposed to be in the same directory, as subdirectories? Is that the volume and why it should be `rw`?

Yes, the backend is linked to `/usr/share/nginx/html` (it creates a `static` folder) and the frontend to `/usr/share/nginx/html/frontend`

**Pull request closed without merging**
